name: 'terminology'
version: '1.0.0'
config-version: 2

seed-paths: ["terminology"]

seeds:
  terminology:
    +schema: terminology
      +column_types: 
        code: test1(100)
        description: test2(500)
