name: 'terminology'
version: '1.0.0'
config-version: 2

seed-paths: ["terminology"]

seeds:
  terminology:
    +schema: terminology
    test:
      +column_types: 
        code: varchar(100)
        description: varchar(500)
    icd_10_cm:
      +column_types: 
        icd_10_cm: varchar(100)
        valid_flag: varchar(10)
        short_description: varchar(1000)
        long_description: varchar(1000)
    zipCodes:
      +column_types:
        state_fips: varchar(10)
        state: varchar(25)
        state_abbr: varchar(10)
        zipcode: varchar(10)
        county: varchar(200)
        city: varchar(200)
    zio_code_databse:
      +column_types:
        zip: varchar(20)
        type: varchar(100)
        decommissioned: varchar(100)
        primary_city: varchar(100)
        acceptable_cities: varchar(1000)
        unacceptable_cities: varchar(1000)
        state: varchar(100)
        county: varchar(100)
        timezone: varchar(100)
        area_codes: varchar(100)
        world_region: varchar(100)
        country: varchar(100)
        latitude: varchar(100)
        longitude: varchar(100)
        irs_estimated_population: varchar(25)
